/** Only file to edit for copy or facts. HTML is a projection. */

export const site = Object.freeze({
  origin: "https://maheshauti.com",
  person: {
    name: "Mahesh Auti",
    who: "I help founders go from idea to launch.",
    headline: ["I help founders go", "from", "idea to launch."],
    eyebrow: "Engineer. Builder. In the details.",
    how: "Full-stack development, AI agents, and agent orchestration.",
    intro: "From the first sketch to the systems behind it. I build products people can use, and stay with them through launch.",
    location: "India",
    aside: "Open-source macOS tools and agent systems.",
    photo: {
      src: "/img/mahesh-natural.jpg",
      alt: "Mahesh Auti",
      lightSrc: "/img/mahesh-illustrated.jpg",
      lightAlt: "Illustrated portrait of Mahesh Auti",
    },
  },
  doors: [
    { kind: "x", label: "Talk on X", href: "https://x.com/MaheshBauti" },
    {
      kind: "linkedin",
      label: "Talk on LinkedIn",
      href: "https://www.linkedin.com/in/mahesh-auti-867b68118/",
    },
  ],
  products: [
    {
      name: "VortexFlow",
      tag: "macOS window switcher · MIT",
      oneLiner:
        "Your windows, one shortcut away. A free macOS switcher that keeps your next window within reach, with a mouse button or keyboard shortcut.",
      details: ["Free & open source", "No account", "No telemetry"],
      action: "Explore VortexFlow",
      status: "live",
      url: "https://vortexflow.io/",
      repo: "https://github.com/maheshauti96/VortexFlow",
      logo: "/img/products/vortexflow.png",
      demo: "spiral",
    },
    {
      name: "Limbo",
      tag: "Coding agent session board",
      oneLiner:
        "A little clarity when your agents are busy. Follow Cursor, Claude, Grok, and Codex sessions together, right from your macOS menu bar.",
      details: ["Local signals only", "Open source", "Built for macOS"],
      action: "View Limbo on GitHub",
      status: "live",
      url: "https://github.com/maheshauti96/Limbo",
      repo: "https://github.com/maheshauti96/Limbo",
      logo: "/img/products/limbo.svg",
      logoInk: true,
      demo: "sessions",
    },
  ],
  foundations: [
    {
      code: "01",
      lens: "AI",
      title: "AI-First Thinking",
      body: "I don't bolt a model onto a finished app. I start by asking what an agent should run, what a human should decide, and how we'll know it worked.",
    },
    {
      code: "02",
      lens: "USER",
      title: "User Perspective",
      body: "I start from the person who has to use it. If the click, the wait, or the error doesn't make sense to them, the rest of the stack doesn't matter.",
    },
    {
      code: "03",
      lens: "HANDS",
      title: "Still in the Code",
      body: "A title doesn't move me off the keyboard. I lead by writing the system, including the agents, the full stack, and the path that has to work.",
    },
    {
      code: "04",
      lens: "FINISH",
      title: "Own It Through Launch",
      body: "I stay on the problem until someone can use it. Sketch to shipped. No throwing the hard parts over a wall.",
    },
  ],
  roles: [
    {
      org: "Quattr",
      orgUrl: "https://www.quattr.com/",
      logo: "/img/companies/quattr.png",
      title: "Acting Engineering Manager",
      start: "2026-08",
      end: null,
      location: "Remote",
      notes: [
        "AI search platform covering SEO, AEO, and GEO. I lead the engineering team and still write the systems.",
      ],
    },
    {
      org: "Quattr",
      orgUrl: "https://www.quattr.com/",
      title: "Lead Software Engineer",
      start: "2024-04",
      end: "2026-08",
      location: "Remote",
      notes: [],
    },
    {
      org: "Quattr",
      orgUrl: "https://www.quattr.com/",
      title: "Sr. Full Stack Engineer",
      start: "2023-03",
      end: "2024-04",
      location: "Remote",
      notes: [],
    },
    {
      org: "Springworks",
      orgUrl: "https://www.springworks.in/",
      logo: "/img/companies/springworks.svg",
      title: "Software Development Engineer 2",
      start: "2022-05",
      end: "2023-03",
      location: "Remote",
      notes: ["Node.js and serverless product work."],
    },
    {
      org: "LTI",
      orgUrl: "https://www.ltimindtree.com/",
      logo: "/img/companies/lti.png",
      title: "Senior Product Engineer",
      start: "2021-09",
      end: "2022-05",
      location: "Pune",
      notes: ["Joined through LTI's acquisition of Cuelogic Technologies."],
    },
    {
      org: "Cuelogic Technologies",
      orgUrl: null,
      logo: "/img/companies/cuelogic.png",
      title: "Senior Software Engineer",
      start: "2021-04",
      end: "2021-10",
      location: "Pune",
      notes: [],
    },
    {
      org: "Cuelogic Technologies",
      orgUrl: null,
      title: "Software Engineer",
      start: "2019-04",
      end: "2021-04",
      location: "Pune",
      notes: [],
    },
    {
      org: "Cuelogic Technologies",
      orgUrl: null,
      title: "Junior Software Engineer",
      start: "2018-04",
      end: "2019-04",
      location: "Pune",
      notes: [],
    },
    {
      org: "Cuelogic Technologies",
      orgUrl: null,
      title: "Intern",
      start: "2017-12",
      end: "2018-06",
      location: "Pune",
      notes: [],
    },
  ],
  blog: {
    title: "Notes from the work.",
    description: "Thoughts on AI, engineering, and the decisions behind building useful products.",
  },
  // Add a published post here. The blog and homepage sort entries by date.
  writing: [
    {
      title:
        "The Evaluation Bottleneck: Why Judging AI Output Is Now the Hardest Part of the Job",
      href: "https://www.linkedin.com/pulse/evaluation-bottleneck-why-judging-ai-output-now-hardest-mahesh-auti-gldjf",
      date: "2026-07-29",
      dek: "Generation is cheap. The job is proving the output is right.",
    },
    {
      title: "Stop Underestimating AI Models",
      href: "https://www.linkedin.com/pulse/stop-underestimating-ai-models-mahesh-auti-blmuf",
      date: "2026-07-21",
      dek: "The bottleneck is describing the situation, not the model.",
    },
    {
      title:
        "AI Isn't Just Making Us Work Faster. It's Forcing Us to Think at a Higher Level.",
      href: "https://www.linkedin.com/pulse/ai-isnt-just-making-us-work-faster-its-forcing-think-higher-auti-vlr8f",
      date: "2026-07-16",
      dek: "Habit work compresses. Judgment, systems, and imagination do not.",
    },
  ],
  reach: [
    { kind: "x", label: "X", href: "https://x.com/MaheshBauti" },
    {
      kind: "linkedin",
      label: "LinkedIn",
      href: "https://www.linkedin.com/in/mahesh-auti-867b68118/",
    },
    { kind: "github", label: "GitHub", href: "https://github.com/maheshauti96" },
    { kind: "web", label: "VortexFlow", href: "https://vortexflow.io/" },
  ],
  dns: {
    apexA: [
      "185.199.108.153",
      "185.199.109.153",
      "185.199.110.153",
      "185.199.111.153",
    ],
    wwwCname: "maheshauti96.github.io",
  },
});
